localFolder: 'backup'

sources:
  - title: title1
    hoster: bitbucket
    type: org
    name: team1
    authName: username
    password: password
    
  - title: title2
    hoster: bitbucket
    type: org
    name: team2
    authName: username
    password: password
